Created controls, stats, menu, header & AI
Dev1LtJ/React-Tic-Tac-Toe pull request #1
Opened 2021-04-06 12:49 UTC by Dev1LtJ

@maximsan, Created controls, stats, menu, header & AI.

2021-04-06 15:09 UTC, maximsan requested changes
Looks fine. I left some comments

2021-04-06 15:09 UTC, maximsan commented on src/game/controls/controls.module.css
> +  border-color: #125184;
use `css` variables

2021-04-06 15:09 UTC, maximsan commented on src/game/controls/controls.module.css
> +  background-image: url('../controls/icons/back.svg');
read here how you can add icon as react component https://create-react-app.dev/docs/adding-images-fonts-and-files/

2021-04-06 15:09 UTC, maximsan commented on src/game/game.jsx
> +			this.state = getFromLocalStorage('state') :
do this check in `ComponentDidMount`

2021-04-06 15:09 UTC, maximsan commented on src/game/game.jsx
> +		if (this.state.single === true) return;
wrap return in brackets and `if (this.state.single)` is the same

2021-04-06 15:09 UTC, maximsan commented on src/game/game.jsx
> +			stepNumber: step,
name `step as stepNumber` and you don't need to do this assignment

2021-04-06 15:09 UTC, maximsan commented on src/game/game.jsx
> +			if(ind === index) return ++item;
add brackets around returns

2021-04-06 15:09 UTC, maximsan commented on src/game/game.jsx
> +			</p>
restructure it to avoid repetetive code

2021-04-06 17:22 UTC, maximsan requested changes
I left some comments

2021-04-06 17:22 UTC, maximsan commented on src/game/header/hamburger/hamburger.jsx
> +	let hamburgerClass = hamburgerStatus ? (`${s.hamburger} ${s.active}`) : (`${s.hamburger}`);
you can use ternary operator inside comparison, simplify the code

2021-04-06 17:22 UTC, maximsan commented on src/game/game.jsx
> +		if (squares[a] && squares[a] === squares[b] && squares[a] === squares[c]) return squares[a];
add brackets

2021-04-06 17:22 UTC, maximsan commented on src/game/game.jsx
> +	}
don't repeat the code, avoid repetitive operations

2021-04-07 16:38 UTC, Larkgronick reviewed
Good work! You made great start in studying react. Left some comments, i hope it helps improve your work.

2021-04-07 16:38 UTC, Larkgronick commented on src/game/menu/menu.jsx
> +		let status = this.props.single;
You can train spread approach here. It will be needed during upcoming project.
For example:
`const{ single } = this.props`

2021-04-07 16:38 UTC, Larkgronick commented on src/game/score/score.jsx
> +    let score = props.score;
Looks like 'score' variable doesn't changes. Use const instead.

2021-04-07 16:38 UTC, Larkgronick commented on src/game/board/square/square.jsx
> +}
Example of using props spreading:

```
export function Square({ onClick, value }) {
	return (
		<button className={s.square} onClick={onClick}>
			{value}
		</button>
	);
}
```

2021-04-08 10:44 UTC, YauhenKoipish commented on src/game/score/score.jsx
> +    let score = props.score;
or use destructurization
```suggestion
    export function Score ({score, single}) {
```

2021-04-09 10:26 UTC, Dev1LtJ commented on src/game/board/board.jsx
> +			<div>
```suggestion
	render() {
		return (
			<React.Fragment>
				<div className={s.board__row}>
          				{this.renderSquare(0)}
					{this.renderSquare(1)}
					{this.renderSquare(2)}
        			</div>
        			<div className={s.board__row}>
          				{this.renderSquare(3)}
          				{this.renderSquare(4)}
          				{this.renderSquare(5)}
        			</div>
        			<div className={s.board__row}>
          				{this.renderSquare(6)}
          				{this.renderSquare(7)}
          				{this.renderSquare(8)}
        			</div>
			</React.Fragment>
		);
	}
```

2021-04-09 10:30 UTC, Dev1LtJ commented on src/game/board/board.jsx
> +import s from "./board.module.css";
Proposed solution:
```suggestion
import styles from "./board.module.css";
```

2021-04-09 10:34 UTC, Dev1LtJ commented on src/game/board/board.module.css
> +  clear: both;
Proposed solution:

```suggestion
  .board__row {
  display: flex;
}
```

2021-04-09 10:36 UTC, Dev1LtJ commented on src/game/board/square/square.module.css
> +  float: left;
With a fix in board.module.css it's no need to use anything else here: 

```suggestion
.square {
  background: #fff;
  border: 2px solid #999;
  font-size: 90px;
  font-weight: bold;
  line-height: 90px;
  height: 100px;
  margin-right: -1px;
  margin-top: -1px;
  padding: 0;
  text-align: center;
  width: 100px;
}
```

2021-04-09 10:39 UTC, Dev1LtJ commented on src/game/board/square/square.module.css
> +  margin-top: -1px;
It's a flex-boxes (with divs), instead of td. And every square is a button.

2021-04-09 11:39 UTC, Dev1LtJ commented on src/game/game.jsx
> +			this.state = getFromLocalStorage('state') :
Thx for the good advice! Proposed solution:

```suggestion
export class Game extends React.Component {
	constructor(props) {
		super(props);
   	 	this.state = {
        		history: [
        		{
        		squares: Array(9).fill(null)
        		}
        		],
        		stepNumber: 0,
        		xIsNext: true,
        		single: false,
        		isMenuOpen: true,
        		score: [0, 0],
    		}
		this.cleanHistory = this.cleanHistory.bind(this);
		this.jumpTo = this.jumpTo.bind(this);
		this.changeMode = this.changeMode.bind(this);
		this.toggleMenu = this.toggleMenu.bind(this);
		this.changeScore = this.changeScore.bind(this);
		this.resetScore = this.resetScore.bind(this);
	}

  	componentDidMount() {
    		let stateObj = getFromLocalStorage('state');
    		if (stateObj) {this.setState(stateObj)};
  	}
```

2021-04-09 11:41 UTC, Dev1LtJ commented on src/game/game.jsx
> +		if (this.state.single === true) return;
Done :)
```suggestion
	jumpTo(step) {
		if (this.state.single) { return };
		this.setState({
			stepNumber: step,
			xIsNext: step % 2 === 0
		});
	}
```

2021-04-09 11:44 UTC, Dev1LtJ commented on src/game/game.jsx
> +			if(ind === index) return ++item;
Done:)

```suggestion
changeScore(index) {
	return this.state.score.map((item, ind) => {
		if(ind === index) { return ++item };
		{ return item };
	});
}
```

2021-04-09 11:49 UTC, Dev1LtJ commented on src/game/game.jsx
> +			stepNumber: step,
Like this?

```suggestion
jumpTo(stepNumber) {
	if (this.state.single) { return };
	this.setState({
 		stepNumber,
		xIsNext: stepNumber % 2 === 0
	});
}
```

2021-04-09 11:53 UTC, Dev1LtJ commented on src/game/game.jsx
> +			</p>
Ok! Should it look like this?

```suggestion
        <span style={this.state.xIsNext ? { color: "red" }: {color: "blue"}}> {this.state.xIsNext ? 'Player X' : 'Player Y'} </span>
```

2021-04-09 12:52 UTC, maximsan commented on src/game/game.jsx
> +			</p>
`
<span style={{ color: this.state.xIsNext  ? "red" :  "blue"}}> {`Player ${this.state.xIsNext ? X : Y}`} </span>
`

2021-04-09 12:55 UTC, maximsan commented on src/game/game.jsx
> +			if(ind === index) return ++item;
It's not almost right. You need to change it to 
```
if (ind === index) { 
    return ++item 
};
return item;
```

2021-04-09 12:56 UTC, maximsan commented on src/game/game.jsx
> +		if (this.state.single === true) return;
Please, place code on different lines

2021-04-09 12:57 UTC, maximsan commented on src/game/game.jsx
> +			this.state = getFromLocalStorage('state') :
```
if (stateObj) {
   this.setState(stateObj)
};
```

2021-04-09 12:58 UTC, maximsan commented on src/game/board/square/square.module.css
> +  float: left;
good to hear

2021-04-09 12:59 UTC, maximsan commented on src/game/board/board.jsx
> +			<div>
good boy :)

2021-04-09 13:08 UTC, Dev1LtJ commented on src/game/header/hamburger/hamburger.jsx
> +	let hamburgerClass = hamburgerStatus ? (`${s.hamburger} ${s.active}`) : (`${s.hamburger}`);
Should it look like this?

```suggestion
let hamburgerClass = `${styles.hamburger} ${props.isMenuOpen ? styles.active : ''}`;
```

2021-04-09 13:13 UTC, Dev1LtJ commented on src/game/game.jsx
> +		if (squares[a] && squares[a] === squares[b] && squares[a] === squares[c]) return squares[a];
Solved
```suggestion
if (squares[a] && squares[a] === squares[b] && squares[a] === squares[c]) { return squares[a] };
```

2021-04-09 13:24 UTC, Dev1LtJ commented on src/game/game.jsx
> +			this.state = getFromLocalStorage('state') :
Okay!)

```suggestion
  componentDidMount() {
    let stateObj = getFromLocalStorage('state');
    if (stateObj) {
      this.setState(stateObj)
    };
  }
```

2021-04-09 13:27 UTC, Dev1LtJ commented on src/game/game.jsx
> +		if (this.state.single === true) return;
Done!)

```suggestion
jumpTo(stepNumber) {
	if (this.state.single) { 
	return;
	}
	this.setState({
		stepNumber,
		xIsNext: stepNumber % 2 === 0
	});
}
```

2021-04-09 13:28 UTC, Dev1LtJ commented on src/game/game.jsx
> +			if(ind === index) return ++item;
Completed

```suggestion
changeScore(index) {
	return this.state.score.map((item, ind) => {
		if(ind === index) {
			return ++item
		};
		return item;
	});
}
```

2021-04-09 13:39 UTC, Dev1LtJ commented on src/game/score/score.jsx
> +    let score = props.score;
Thx! I took into account both advices :)

```suggestion
export function Score ({single, score, onClick}) {
    const gameMode = single ? 'SinglePlayer' : 'MultiPlayer';
    
    return (
        <div className={styles.score__container}>
            <div className={styles.score__gametitle}>Game mode:</div>
            <div className={styles.score__gamemode}>{gameMode}</div>
            <div className={styles.score__scoretitle}>Score:</div>
            <div className={styles.score__scorevalue}>
                <span style={{color: 'red'}}>{score[0]} </span>:
                <span style={{color: 'blue'}}> {score[1]}</span>
            </div>
            <button className={styles.score__button} onClick={onClick}>Reset score</button>
        </div>
    );
}
```

2021-04-09 13:41 UTC, Dev1LtJ commented on src/game/board/square/square.jsx
> +}
Optimized :)
```suggestion
export function Square({onClick, value}) {
	return (
		<button className={styles.square} onClick={onClick}>
			{value}
		</button>
	);
}
```

2021-04-09 13:51 UTC, Dev1LtJ commented on src/game/menu/menu.jsx
> +		let status = this.props.single;
Good idea! Thx, but i read, that this approach is called "destructuring assignment", isn't it? 
```suggestion
render () {
	let {single, isMenuOpen} = this.props;
	let buttonName = {single} ? 'SinglePlayer' : 'MultiPlayer';
	let menuClass =  `${styles.menu__container} ${isMenuOpen ? styles.active : ''}`;
```

2021-04-09 13:56 UTC, Dev1LtJ commented on src/game/board/square/square.module.css
> +  background: #ddd;
fixed! :)
```suggestion
background: var(--color-white);
```

2021-04-09 13:57 UTC, Dev1LtJ commented on src/game/controls/controls.module.css
> +  border-color: #125184;
Solved!)
```suggestion
border-color: var(--blue-color);
```

2021-04-09 18:02 UTC, Dev1LtJ commented on src/game/controls/controls.jsx
> +          onClick={()=> this.handleClick(--currentStep)}
Fixed it!

```suggestion
          onClick={()=> this.moveBack(currentStep)}
```

2021-04-09 18:02 UTC, Dev1LtJ commented on src/game/controls/controls.jsx
> +          onClick={()=> this.handleClick(++currentStep)}
Also fixed!
```suggestion
         onClick={()=> this.moveForward(currentStep)}
```

2021-04-09 18:07 UTC, Dev1LtJ commented on src/game/controls/controls.module.css
> +  background-image: url('../controls/icons/back.svg');
fixed? 
```suggestion
.controls__button_undo {
	background-image: url("./icons/back.svg");
}

.controls__button_redo {
	background-image: url("./icons/next.svg");
}

.controls__button_reset {
	background-image: url("./icons/refresh.svg");
}
```

2021-04-09 19:05 UTC, Larkgronick commented on src/game/menu/menu.jsx
> +		let status = this.props.single;
Yes, you are right, its destructuring assignment and its will be used in your project.

2021-04-09 19:06 UTC, Larkgronick approved these changes

2021-04-11 17:07 UTC, maximsan commented on src/game/header/hamburger/hamburger.jsx
> +	let hamburgerClass = hamburgerStatus ? (`${s.hamburger} ${s.active}`) : (`${s.hamburger}`);
Yep!

2021-04-11 17:08 UTC, maximsan commented on src/game/game.jsx
> +			if(ind === index) return ++item;
awesome

2021-04-11 17:09 UTC, maximsan approved these changes
Looks better.

2021-04-12 16:44 UTC, Dev1LtJ commented on src/game/game.jsx
> +	}
omg! I did it :)) optimized from 91 lines to 32. How it looks? :))
```suggestion
function doAITurn (array, huSymbol, aiSymbol) {
	const moveMatrix = [
		[0, 1, 2],
		[3, 4, 5],
		[6, 7, 8],
		[0, 3, 6],
		[1, 4, 7],
		[2, 5, 8],
		[0, 4, 8],
		[2, 4, 6],
	];

	for (let i = 0; i < moveMatrix.length; i++) {
		const [a, b, c] = moveMatrix[i];
		if (array[a] === array[b] && (array[a] !== null && array[b] !== null) && array[c] === null) {
			return c;
		} else if (array[b] === array[c] && (array[b] !== null && array[c] !== null) && array[a] === null) {
			return a;
		} else if (array[a] === array[c] && (array[a] !== null && array[c] !== null) && array[b] === null) {
			return b;
		} 
	}

	if (array[4] !== aiSymbol && array[4] !== huSymbol) {
		return 4;
	}
	
	for (let i = 1; i <= 8; i++) {
		if (array[i] !== huSymbol && array[i] !== aiSymbol) {
			return i;
		}
	}
}
```

2021-04-12 19:56 UTC, merged